#!/usr/bin/env python3
import parser.parse as p
import parser.RelAlgeTree as RAT

p.table = {
	"\x19 :=  ● query \x18": {
		"SELECT": "query := SELECT ● idlist FROM idlist",
		"FROM": None,
		"WILDCARD": None,
		"WHERE": None,
		"ID": None,
		"COMMA": None,
		"PLUS": None,
		"MINUS": None,
		"DIVIDE": None,
		"EXPONENT": None,
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": None,
		"LPAREN": None,
		"RPAREN": None,
		"NUMBER": None,
		"BOOL": None,
		"\x18": None,
		"query": "\x19 := query ● \x18",
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": None,
		"\x19": None,
	},
	"\x19 := query ● \x18": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": None,
		"WHERE": None,
		"ID": None,
		"COMMA": None,
		"PLUS": None,
		"MINUS": None,
		"DIVIDE": None,
		"EXPONENT": None,
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": None,
		"LPAREN": None,
		"RPAREN": None,
		"NUMBER": None,
		"BOOL": None,
		"\x18": "accept",
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": None,
		"\x19": None,
	},
	"query := SELECT ● idlist FROM idlist": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": "query := SELECT WILDCARD ● FROM idlist",
		"WHERE": None,
		"ID": "idlist := ID ● ",
		"COMMA": None,
		"PLUS": None,
		"MINUS": None,
		"DIVIDE": None,
		"EXPONENT": None,
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": None,
		"LPAREN": None,
		"RPAREN": None,
		"NUMBER": None,
		"BOOL": None,
		"\x18": None,
		"query": None,
		"idlist": "query := SELECT idlist ● FROM idlist",
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": None,
		"\x19": None,
	},
	"query := SELECT idlist ● FROM idlist": {
		"SELECT": None,
		"FROM": "query := SELECT idlist FROM ● idlist",
		"WILDCARD": None,
		"WHERE": None,
		"ID": None,
		"COMMA": "idlist := idlist COMMA ● ID",
		"PLUS": None,
		"MINUS": None,
		"DIVIDE": None,
		"EXPONENT": None,
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": None,
		"LPAREN": None,
		"RPAREN": None,
		"NUMBER": None,
		"BOOL": None,
		"\x18": None,
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": None,
		"\x19": None,
	},
	"query := SELECT idlist FROM ● idlist": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": None,
		"WHERE": None,
		"ID": "idlist := ID ● ",
		"COMMA": None,
		"PLUS": None,
		"MINUS": None,
		"DIVIDE": None,
		"EXPONENT": None,
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": None,
		"LPAREN": None,
		"RPAREN": None,
		"NUMBER": None,
		"BOOL": None,
		"\x18": None,
		"query": None,
		"idlist": "query := SELECT idlist FROM idlist ● ",
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": None,
		"\x19": None,
	},
	"query := SELECT idlist FROM idlist ● ": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": None,
		"WHERE": "query := SELECT idlist FROM idlist WHERE ● predicate",
		"ID": None,
		"COMMA": "idlist := idlist COMMA ● ID",
		"PLUS": None,
		"MINUS": None,
		"DIVIDE": None,
		"EXPONENT": None,
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": None,
		"LPAREN": None,
		"RPAREN": None,
		"NUMBER": None,
		"BOOL": None,
		"\x18": ('query', 4),
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": None,
		"\x19": None,
	},
	"idlist := idlist COMMA ● ID": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": None,
		"WHERE": None,
		"ID": "idlist := idlist COMMA ID ● ",
		"COMMA": None,
		"PLUS": None,
		"MINUS": None,
		"DIVIDE": None,
		"EXPONENT": None,
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": None,
		"LPAREN": None,
		"RPAREN": None,
		"NUMBER": None,
		"BOOL": None,
		"\x18": None,
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": None,
		"\x19": None,
	},
	"idlist := idlist COMMA ID ● ": {
		"SELECT": None,
		"FROM": ('idlist', 3),
		"WILDCARD": None,
		"WHERE": ('idlist', 3),
		"ID": None,
		"COMMA": ('idlist', 3),
		"PLUS": None,
		"MINUS": None,
		"DIVIDE": None,
		"EXPONENT": None,
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": None,
		"LPAREN": None,
		"RPAREN": None,
		"NUMBER": None,
		"BOOL": None,
		"\x18": ('idlist', 3),
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": None,
		"\x19": None,
	},
	"idlist := ID ● ": {
		"SELECT": None,
		"FROM": ('idlist', 1),
		"WILDCARD": None,
		"WHERE": ('idlist', 1),
		"ID": None,
		"COMMA": ('idlist', 1),
		"PLUS": None,
		"MINUS": None,
		"DIVIDE": None,
		"EXPONENT": None,
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": None,
		"LPAREN": None,
		"RPAREN": None,
		"NUMBER": None,
		"BOOL": None,
		"\x18": ('idlist', 1),
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": None,
		"\x19": None,
	},
	"query := SELECT WILDCARD ● FROM idlist": {
		"SELECT": None,
		"FROM": "query := SELECT WILDCARD FROM ● idlist",
		"WILDCARD": None,
		"WHERE": None,
		"ID": None,
		"COMMA": None,
		"PLUS": None,
		"MINUS": None,
		"DIVIDE": None,
		"EXPONENT": None,
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": None,
		"LPAREN": None,
		"RPAREN": None,
		"NUMBER": None,
		"BOOL": None,
		"\x18": None,
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": None,
		"\x19": None,
	},
	"query := SELECT WILDCARD FROM ● idlist": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": None,
		"WHERE": None,
		"ID": "idlist := ID ● ",
		"COMMA": None,
		"PLUS": None,
		"MINUS": None,
		"DIVIDE": None,
		"EXPONENT": None,
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": None,
		"LPAREN": None,
		"RPAREN": None,
		"NUMBER": None,
		"BOOL": None,
		"\x18": None,
		"query": None,
		"idlist": "query := SELECT WILDCARD FROM idlist ● ",
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": None,
		"\x19": None,
	},
	"query := SELECT WILDCARD FROM idlist ● ": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": None,
		"WHERE": "query := SELECT WILDCARD FROM idlist WHERE ● predicate",
		"ID": None,
		"COMMA": "idlist := idlist COMMA ● ID",
		"PLUS": None,
		"MINUS": None,
		"DIVIDE": None,
		"EXPONENT": None,
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": None,
		"LPAREN": None,
		"RPAREN": None,
		"NUMBER": None,
		"BOOL": None,
		"\x18": ('query', 4),
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": None,
		"\x19": None,
	},
	"query := SELECT idlist FROM idlist WHERE ● predicate": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": None,
		"WHERE": None,
		"ID": "term := ID ● ",
		"COMMA": None,
		"PLUS": "z := PLUS ● term",
		"MINUS": "z := MINUS ● term",
		"DIVIDE": None,
		"EXPONENT": None,
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": "z := NOT ● term",
		"LPAREN": "term := LPAREN ● predicate RPAREN",
		"RPAREN": None,
		"NUMBER": "term := NUMBER ● ",
		"BOOL": "term := BOOL ● ",
		"\x18": None,
		"query": None,
		"idlist": None,
		"predicate": "query := SELECT idlist FROM idlist WHERE predicate ● ",
		"w": "predicate := w ● PLUS w",
		"x": "w := x ● WILDCARD x",
		"y": "x := y ● EQUALS y",
		"z": "y := z ● AND z",
		"term": "z := term ● ",
		"\x19": None,
	},
	"query := SELECT idlist FROM idlist WHERE predicate ● ": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": None,
		"WHERE": None,
		"ID": None,
		"COMMA": None,
		"PLUS": None,
		"MINUS": None,
		"DIVIDE": None,
		"EXPONENT": None,
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": None,
		"LPAREN": None,
		"RPAREN": None,
		"NUMBER": None,
		"BOOL": None,
		"\x18": ('query', 6),
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": None,
		"\x19": None,
	},
	"predicate := w ● PLUS w": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": None,
		"WHERE": None,
		"ID": None,
		"COMMA": None,
		"PLUS": "predicate := w PLUS ● w",
		"MINUS": "predicate := w MINUS ● w",
		"DIVIDE": None,
		"EXPONENT": None,
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": None,
		"LPAREN": None,
		"RPAREN": ('predicate', 1),
		"NUMBER": None,
		"BOOL": None,
		"\x18": ('predicate', 1),
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": None,
		"\x19": None,
	},
	"predicate := w PLUS ● w": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": None,
		"WHERE": None,
		"ID": "term := ID ● ",
		"COMMA": None,
		"PLUS": "z := PLUS ● term",
		"MINUS": "z := MINUS ● term",
		"DIVIDE": None,
		"EXPONENT": None,
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": "z := NOT ● term",
		"LPAREN": "term := LPAREN ● predicate RPAREN",
		"RPAREN": None,
		"NUMBER": "term := NUMBER ● ",
		"BOOL": "term := BOOL ● ",
		"\x18": None,
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": "predicate := w PLUS w ● ",
		"x": "w := x ● WILDCARD x",
		"y": "x := y ● EQUALS y",
		"z": "y := z ● AND z",
		"term": "z := term ● ",
		"\x19": None,
	},
	"predicate := w PLUS w ● ": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": None,
		"WHERE": None,
		"ID": None,
		"COMMA": None,
		"PLUS": None,
		"MINUS": None,
		"DIVIDE": None,
		"EXPONENT": None,
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": None,
		"LPAREN": None,
		"RPAREN": ('predicate', 3),
		"NUMBER": None,
		"BOOL": None,
		"\x18": ('predicate', 3),
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": None,
		"\x19": None,
	},
	"w := x ● WILDCARD x": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": "w := x WILDCARD ● x",
		"WHERE": None,
		"ID": None,
		"COMMA": None,
		"PLUS": ('w', 1),
		"MINUS": ('w', 1),
		"DIVIDE": "w := x DIVIDE ● x",
		"EXPONENT": "w := x EXPONENT ● x",
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": None,
		"LPAREN": None,
		"RPAREN": ('w', 1),
		"NUMBER": None,
		"BOOL": None,
		"\x18": ('w', 1),
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": None,
		"\x19": None,
	},
	"w := x WILDCARD ● x": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": None,
		"WHERE": None,
		"ID": "term := ID ● ",
		"COMMA": None,
		"PLUS": "z := PLUS ● term",
		"MINUS": "z := MINUS ● term",
		"DIVIDE": None,
		"EXPONENT": None,
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": "z := NOT ● term",
		"LPAREN": "term := LPAREN ● predicate RPAREN",
		"RPAREN": None,
		"NUMBER": "term := NUMBER ● ",
		"BOOL": "term := BOOL ● ",
		"\x18": None,
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": "w := x WILDCARD x ● ",
		"y": "x := y ● EQUALS y",
		"z": "y := z ● AND z",
		"term": "z := term ● ",
		"\x19": None,
	},
	"w := x WILDCARD x ● ": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": None,
		"WHERE": None,
		"ID": None,
		"COMMA": None,
		"PLUS": ('w', 3),
		"MINUS": ('w', 3),
		"DIVIDE": None,
		"EXPONENT": None,
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": None,
		"LPAREN": None,
		"RPAREN": ('w', 3),
		"NUMBER": None,
		"BOOL": None,
		"\x18": ('w', 3),
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": None,
		"\x19": None,
	},
	"x := y ● EQUALS y": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": ('x', 1),
		"WHERE": None,
		"ID": None,
		"COMMA": None,
		"PLUS": ('x', 1),
		"MINUS": ('x', 1),
		"DIVIDE": ('x', 1),
		"EXPONENT": ('x', 1),
		"EQUALS": "x := y EQUALS ● y",
		"NEQUALS": "x := y NEQUALS ● y",
		"LESS": "x := y LESS ● y",
		"LESSEQ": "x := y LESSEQ ● y",
		"GREATER": "x := y GREATER ● y",
		"GREATEREQ": "x := y GREATEREQ ● y",
		"AND": None,
		"OR": None,
		"NOT": None,
		"LPAREN": None,
		"RPAREN": ('x', 1),
		"NUMBER": None,
		"BOOL": None,
		"\x18": ('x', 1),
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": None,
		"\x19": None,
	},
	"x := y EQUALS ● y": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": None,
		"WHERE": None,
		"ID": "term := ID ● ",
		"COMMA": None,
		"PLUS": "z := PLUS ● term",
		"MINUS": "z := MINUS ● term",
		"DIVIDE": None,
		"EXPONENT": None,
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": "z := NOT ● term",
		"LPAREN": "term := LPAREN ● predicate RPAREN",
		"RPAREN": None,
		"NUMBER": "term := NUMBER ● ",
		"BOOL": "term := BOOL ● ",
		"\x18": None,
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": "x := y EQUALS y ● ",
		"z": "y := z ● AND z",
		"term": "z := term ● ",
		"\x19": None,
	},
	"x := y EQUALS y ● ": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": ('x', 3),
		"WHERE": None,
		"ID": None,
		"COMMA": None,
		"PLUS": ('x', 3),
		"MINUS": ('x', 3),
		"DIVIDE": ('x', 3),
		"EXPONENT": ('x', 3),
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": None,
		"LPAREN": None,
		"RPAREN": ('x', 3),
		"NUMBER": None,
		"BOOL": None,
		"\x18": ('x', 3),
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": None,
		"\x19": None,
	},
	"y := z ● AND z": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": ('y', 1),
		"WHERE": None,
		"ID": None,
		"COMMA": None,
		"PLUS": ('y', 1),
		"MINUS": ('y', 1),
		"DIVIDE": ('y', 1),
		"EXPONENT": ('y', 1),
		"EQUALS": ('y', 1),
		"NEQUALS": ('y', 1),
		"LESS": ('y', 1),
		"LESSEQ": ('y', 1),
		"GREATER": ('y', 1),
		"GREATEREQ": ('y', 1),
		"AND": "y := z AND ● z",
		"OR": "y := z OR ● z",
		"NOT": None,
		"LPAREN": None,
		"RPAREN": ('y', 1),
		"NUMBER": None,
		"BOOL": None,
		"\x18": ('y', 1),
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": None,
		"\x19": None,
	},
	"y := z AND ● z": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": None,
		"WHERE": None,
		"ID": "term := ID ● ",
		"COMMA": None,
		"PLUS": "z := PLUS ● term",
		"MINUS": "z := MINUS ● term",
		"DIVIDE": None,
		"EXPONENT": None,
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": "z := NOT ● term",
		"LPAREN": "term := LPAREN ● predicate RPAREN",
		"RPAREN": None,
		"NUMBER": "term := NUMBER ● ",
		"BOOL": "term := BOOL ● ",
		"\x18": None,
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": "y := z AND z ● ",
		"term": "z := term ● ",
		"\x19": None,
	},
	"y := z AND z ● ": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": ('y', 3),
		"WHERE": None,
		"ID": None,
		"COMMA": None,
		"PLUS": ('y', 3),
		"MINUS": ('y', 3),
		"DIVIDE": ('y', 3),
		"EXPONENT": ('y', 3),
		"EQUALS": ('y', 3),
		"NEQUALS": ('y', 3),
		"LESS": ('y', 3),
		"LESSEQ": ('y', 3),
		"GREATER": ('y', 3),
		"GREATEREQ": ('y', 3),
		"AND": None,
		"OR": None,
		"NOT": None,
		"LPAREN": None,
		"RPAREN": ('y', 3),
		"NUMBER": None,
		"BOOL": None,
		"\x18": ('y', 3),
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": None,
		"\x19": None,
	},
	"z := term ● ": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": ('z', 1),
		"WHERE": None,
		"ID": None,
		"COMMA": None,
		"PLUS": ('z', 1),
		"MINUS": ('z', 1),
		"DIVIDE": ('z', 1),
		"EXPONENT": ('z', 1),
		"EQUALS": ('z', 1),
		"NEQUALS": ('z', 1),
		"LESS": ('z', 1),
		"LESSEQ": ('z', 1),
		"GREATER": ('z', 1),
		"GREATEREQ": ('z', 1),
		"AND": ('z', 1),
		"OR": ('z', 1),
		"NOT": None,
		"LPAREN": None,
		"RPAREN": ('z', 1),
		"NUMBER": None,
		"BOOL": None,
		"\x18": ('z', 1),
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": None,
		"\x19": None,
	},
	"term := ID ● ": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": ('term', 1),
		"WHERE": None,
		"ID": None,
		"COMMA": None,
		"PLUS": ('term', 1),
		"MINUS": ('term', 1),
		"DIVIDE": ('term', 1),
		"EXPONENT": ('term', 1),
		"EQUALS": ('term', 1),
		"NEQUALS": ('term', 1),
		"LESS": ('term', 1),
		"LESSEQ": ('term', 1),
		"GREATER": ('term', 1),
		"GREATEREQ": ('term', 1),
		"AND": ('term', 1),
		"OR": ('term', 1),
		"NOT": None,
		"LPAREN": None,
		"RPAREN": ('term', 1),
		"NUMBER": None,
		"BOOL": None,
		"\x18": ('term', 1),
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": None,
		"\x19": None,
	},
	"z := PLUS ● term": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": None,
		"WHERE": None,
		"ID": "term := ID ● ",
		"COMMA": None,
		"PLUS": None,
		"MINUS": None,
		"DIVIDE": None,
		"EXPONENT": None,
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": None,
		"LPAREN": "term := LPAREN ● predicate RPAREN",
		"RPAREN": None,
		"NUMBER": "term := NUMBER ● ",
		"BOOL": "term := BOOL ● ",
		"\x18": None,
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": "z := PLUS term ● ",
		"\x19": None,
	},
	"z := PLUS term ● ": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": ('z', 2),
		"WHERE": None,
		"ID": None,
		"COMMA": None,
		"PLUS": ('z', 2),
		"MINUS": ('z', 2),
		"DIVIDE": ('z', 2),
		"EXPONENT": ('z', 2),
		"EQUALS": ('z', 2),
		"NEQUALS": ('z', 2),
		"LESS": ('z', 2),
		"LESSEQ": ('z', 2),
		"GREATER": ('z', 2),
		"GREATEREQ": ('z', 2),
		"AND": ('z', 2),
		"OR": ('z', 2),
		"NOT": None,
		"LPAREN": None,
		"RPAREN": ('z', 2),
		"NUMBER": None,
		"BOOL": None,
		"\x18": ('z', 2),
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": None,
		"\x19": None,
	},
	"term := LPAREN ● predicate RPAREN": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": None,
		"WHERE": None,
		"ID": "term := ID ● ",
		"COMMA": None,
		"PLUS": "z := PLUS ● term",
		"MINUS": "z := MINUS ● term",
		"DIVIDE": None,
		"EXPONENT": None,
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": "z := NOT ● term",
		"LPAREN": "term := LPAREN ● predicate RPAREN",
		"RPAREN": None,
		"NUMBER": "term := NUMBER ● ",
		"BOOL": "term := BOOL ● ",
		"\x18": None,
		"query": None,
		"idlist": None,
		"predicate": "term := LPAREN predicate ● RPAREN",
		"w": "predicate := w ● PLUS w",
		"x": "w := x ● WILDCARD x",
		"y": "x := y ● EQUALS y",
		"z": "y := z ● AND z",
		"term": "z := term ● ",
		"\x19": None,
	},
	"term := LPAREN predicate ● RPAREN": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": None,
		"WHERE": None,
		"ID": None,
		"COMMA": None,
		"PLUS": None,
		"MINUS": None,
		"DIVIDE": None,
		"EXPONENT": None,
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": None,
		"LPAREN": None,
		"RPAREN": "term := LPAREN predicate RPAREN ● ",
		"NUMBER": None,
		"BOOL": None,
		"\x18": None,
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": None,
		"\x19": None,
	},
	"term := LPAREN predicate RPAREN ● ": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": ('term', 3),
		"WHERE": None,
		"ID": None,
		"COMMA": None,
		"PLUS": ('term', 3),
		"MINUS": ('term', 3),
		"DIVIDE": ('term', 3),
		"EXPONENT": ('term', 3),
		"EQUALS": ('term', 3),
		"NEQUALS": ('term', 3),
		"LESS": ('term', 3),
		"LESSEQ": ('term', 3),
		"GREATER": ('term', 3),
		"GREATEREQ": ('term', 3),
		"AND": ('term', 3),
		"OR": ('term', 3),
		"NOT": None,
		"LPAREN": None,
		"RPAREN": ('term', 3),
		"NUMBER": None,
		"BOOL": None,
		"\x18": ('term', 3),
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": None,
		"\x19": None,
	},
	"predicate := w MINUS ● w": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": None,
		"WHERE": None,
		"ID": "term := ID ● ",
		"COMMA": None,
		"PLUS": "z := PLUS ● term",
		"MINUS": "z := MINUS ● term",
		"DIVIDE": None,
		"EXPONENT": None,
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": "z := NOT ● term",
		"LPAREN": "term := LPAREN ● predicate RPAREN",
		"RPAREN": None,
		"NUMBER": "term := NUMBER ● ",
		"BOOL": "term := BOOL ● ",
		"\x18": None,
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": "predicate := w MINUS w ● ",
		"x": "w := x ● WILDCARD x",
		"y": "x := y ● EQUALS y",
		"z": "y := z ● AND z",
		"term": "z := term ● ",
		"\x19": None,
	},
	"predicate := w MINUS w ● ": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": None,
		"WHERE": None,
		"ID": None,
		"COMMA": None,
		"PLUS": None,
		"MINUS": None,
		"DIVIDE": None,
		"EXPONENT": None,
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": None,
		"LPAREN": None,
		"RPAREN": ('predicate', 3),
		"NUMBER": None,
		"BOOL": None,
		"\x18": ('predicate', 3),
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": None,
		"\x19": None,
	},
	"w := x DIVIDE ● x": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": None,
		"WHERE": None,
		"ID": "term := ID ● ",
		"COMMA": None,
		"PLUS": "z := PLUS ● term",
		"MINUS": "z := MINUS ● term",
		"DIVIDE": None,
		"EXPONENT": None,
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": "z := NOT ● term",
		"LPAREN": "term := LPAREN ● predicate RPAREN",
		"RPAREN": None,
		"NUMBER": "term := NUMBER ● ",
		"BOOL": "term := BOOL ● ",
		"\x18": None,
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": "w := x DIVIDE x ● ",
		"y": "x := y ● EQUALS y",
		"z": "y := z ● AND z",
		"term": "z := term ● ",
		"\x19": None,
	},
	"w := x DIVIDE x ● ": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": None,
		"WHERE": None,
		"ID": None,
		"COMMA": None,
		"PLUS": ('w', 3),
		"MINUS": ('w', 3),
		"DIVIDE": None,
		"EXPONENT": None,
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": None,
		"LPAREN": None,
		"RPAREN": ('w', 3),
		"NUMBER": None,
		"BOOL": None,
		"\x18": ('w', 3),
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": None,
		"\x19": None,
	},
	"x := y NEQUALS ● y": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": None,
		"WHERE": None,
		"ID": "term := ID ● ",
		"COMMA": None,
		"PLUS": "z := PLUS ● term",
		"MINUS": "z := MINUS ● term",
		"DIVIDE": None,
		"EXPONENT": None,
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": "z := NOT ● term",
		"LPAREN": "term := LPAREN ● predicate RPAREN",
		"RPAREN": None,
		"NUMBER": "term := NUMBER ● ",
		"BOOL": "term := BOOL ● ",
		"\x18": None,
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": "x := y NEQUALS y ● ",
		"z": "y := z ● AND z",
		"term": "z := term ● ",
		"\x19": None,
	},
	"x := y NEQUALS y ● ": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": ('x', 3),
		"WHERE": None,
		"ID": None,
		"COMMA": None,
		"PLUS": ('x', 3),
		"MINUS": ('x', 3),
		"DIVIDE": ('x', 3),
		"EXPONENT": ('x', 3),
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": None,
		"LPAREN": None,
		"RPAREN": ('x', 3),
		"NUMBER": None,
		"BOOL": None,
		"\x18": ('x', 3),
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": None,
		"\x19": None,
	},
	"y := z OR ● z": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": None,
		"WHERE": None,
		"ID": "term := ID ● ",
		"COMMA": None,
		"PLUS": "z := PLUS ● term",
		"MINUS": "z := MINUS ● term",
		"DIVIDE": None,
		"EXPONENT": None,
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": "z := NOT ● term",
		"LPAREN": "term := LPAREN ● predicate RPAREN",
		"RPAREN": None,
		"NUMBER": "term := NUMBER ● ",
		"BOOL": "term := BOOL ● ",
		"\x18": None,
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": "y := z OR z ● ",
		"term": "z := term ● ",
		"\x19": None,
	},
	"y := z OR z ● ": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": ('y', 3),
		"WHERE": None,
		"ID": None,
		"COMMA": None,
		"PLUS": ('y', 3),
		"MINUS": ('y', 3),
		"DIVIDE": ('y', 3),
		"EXPONENT": ('y', 3),
		"EQUALS": ('y', 3),
		"NEQUALS": ('y', 3),
		"LESS": ('y', 3),
		"LESSEQ": ('y', 3),
		"GREATER": ('y', 3),
		"GREATEREQ": ('y', 3),
		"AND": None,
		"OR": None,
		"NOT": None,
		"LPAREN": None,
		"RPAREN": ('y', 3),
		"NUMBER": None,
		"BOOL": None,
		"\x18": ('y', 3),
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": None,
		"\x19": None,
	},
	"z := MINUS ● term": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": None,
		"WHERE": None,
		"ID": "term := ID ● ",
		"COMMA": None,
		"PLUS": None,
		"MINUS": None,
		"DIVIDE": None,
		"EXPONENT": None,
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": None,
		"LPAREN": "term := LPAREN ● predicate RPAREN",
		"RPAREN": None,
		"NUMBER": "term := NUMBER ● ",
		"BOOL": "term := BOOL ● ",
		"\x18": None,
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": "z := MINUS term ● ",
		"\x19": None,
	},
	"z := MINUS term ● ": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": ('z', 2),
		"WHERE": None,
		"ID": None,
		"COMMA": None,
		"PLUS": ('z', 2),
		"MINUS": ('z', 2),
		"DIVIDE": ('z', 2),
		"EXPONENT": ('z', 2),
		"EQUALS": ('z', 2),
		"NEQUALS": ('z', 2),
		"LESS": ('z', 2),
		"LESSEQ": ('z', 2),
		"GREATER": ('z', 2),
		"GREATEREQ": ('z', 2),
		"AND": ('z', 2),
		"OR": ('z', 2),
		"NOT": None,
		"LPAREN": None,
		"RPAREN": ('z', 2),
		"NUMBER": None,
		"BOOL": None,
		"\x18": ('z', 2),
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": None,
		"\x19": None,
	},
	"term := NUMBER ● ": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": ('term', 1),
		"WHERE": None,
		"ID": None,
		"COMMA": None,
		"PLUS": ('term', 1),
		"MINUS": ('term', 1),
		"DIVIDE": ('term', 1),
		"EXPONENT": ('term', 1),
		"EQUALS": ('term', 1),
		"NEQUALS": ('term', 1),
		"LESS": ('term', 1),
		"LESSEQ": ('term', 1),
		"GREATER": ('term', 1),
		"GREATEREQ": ('term', 1),
		"AND": ('term', 1),
		"OR": ('term', 1),
		"NOT": None,
		"LPAREN": None,
		"RPAREN": ('term', 1),
		"NUMBER": None,
		"BOOL": None,
		"\x18": ('term', 1),
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": None,
		"\x19": None,
	},
	"term := BOOL ● ": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": ('term', 1),
		"WHERE": None,
		"ID": None,
		"COMMA": None,
		"PLUS": ('term', 1),
		"MINUS": ('term', 1),
		"DIVIDE": ('term', 1),
		"EXPONENT": ('term', 1),
		"EQUALS": ('term', 1),
		"NEQUALS": ('term', 1),
		"LESS": ('term', 1),
		"LESSEQ": ('term', 1),
		"GREATER": ('term', 1),
		"GREATEREQ": ('term', 1),
		"AND": ('term', 1),
		"OR": ('term', 1),
		"NOT": None,
		"LPAREN": None,
		"RPAREN": ('term', 1),
		"NUMBER": None,
		"BOOL": None,
		"\x18": ('term', 1),
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": None,
		"\x19": None,
	},
	"z := NOT ● term": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": None,
		"WHERE": None,
		"ID": "term := ID ● ",
		"COMMA": None,
		"PLUS": None,
		"MINUS": None,
		"DIVIDE": None,
		"EXPONENT": None,
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": None,
		"LPAREN": "term := LPAREN ● predicate RPAREN",
		"RPAREN": None,
		"NUMBER": "term := NUMBER ● ",
		"BOOL": "term := BOOL ● ",
		"\x18": None,
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": "z := NOT term ● ",
		"\x19": None,
	},
	"z := NOT term ● ": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": ('z', 2),
		"WHERE": None,
		"ID": None,
		"COMMA": None,
		"PLUS": ('z', 2),
		"MINUS": ('z', 2),
		"DIVIDE": ('z', 2),
		"EXPONENT": ('z', 2),
		"EQUALS": ('z', 2),
		"NEQUALS": ('z', 2),
		"LESS": ('z', 2),
		"LESSEQ": ('z', 2),
		"GREATER": ('z', 2),
		"GREATEREQ": ('z', 2),
		"AND": ('z', 2),
		"OR": ('z', 2),
		"NOT": None,
		"LPAREN": None,
		"RPAREN": ('z', 2),
		"NUMBER": None,
		"BOOL": None,
		"\x18": ('z', 2),
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": None,
		"\x19": None,
	},
	"x := y LESS ● y": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": None,
		"WHERE": None,
		"ID": "term := ID ● ",
		"COMMA": None,
		"PLUS": "z := PLUS ● term",
		"MINUS": "z := MINUS ● term",
		"DIVIDE": None,
		"EXPONENT": None,
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": "z := NOT ● term",
		"LPAREN": "term := LPAREN ● predicate RPAREN",
		"RPAREN": None,
		"NUMBER": "term := NUMBER ● ",
		"BOOL": "term := BOOL ● ",
		"\x18": None,
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": "x := y LESS y ● ",
		"z": "y := z ● AND z",
		"term": "z := term ● ",
		"\x19": None,
	},
	"x := y LESS y ● ": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": ('x', 3),
		"WHERE": None,
		"ID": None,
		"COMMA": None,
		"PLUS": ('x', 3),
		"MINUS": ('x', 3),
		"DIVIDE": ('x', 3),
		"EXPONENT": ('x', 3),
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": None,
		"LPAREN": None,
		"RPAREN": ('x', 3),
		"NUMBER": None,
		"BOOL": None,
		"\x18": ('x', 3),
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": None,
		"\x19": None,
	},
	"x := y LESSEQ ● y": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": None,
		"WHERE": None,
		"ID": "term := ID ● ",
		"COMMA": None,
		"PLUS": "z := PLUS ● term",
		"MINUS": "z := MINUS ● term",
		"DIVIDE": None,
		"EXPONENT": None,
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": "z := NOT ● term",
		"LPAREN": "term := LPAREN ● predicate RPAREN",
		"RPAREN": None,
		"NUMBER": "term := NUMBER ● ",
		"BOOL": "term := BOOL ● ",
		"\x18": None,
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": "x := y LESSEQ y ● ",
		"z": "y := z ● AND z",
		"term": "z := term ● ",
		"\x19": None,
	},
	"x := y LESSEQ y ● ": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": ('x', 3),
		"WHERE": None,
		"ID": None,
		"COMMA": None,
		"PLUS": ('x', 3),
		"MINUS": ('x', 3),
		"DIVIDE": ('x', 3),
		"EXPONENT": ('x', 3),
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": None,
		"LPAREN": None,
		"RPAREN": ('x', 3),
		"NUMBER": None,
		"BOOL": None,
		"\x18": ('x', 3),
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": None,
		"\x19": None,
	},
	"x := y GREATER ● y": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": None,
		"WHERE": None,
		"ID": "term := ID ● ",
		"COMMA": None,
		"PLUS": "z := PLUS ● term",
		"MINUS": "z := MINUS ● term",
		"DIVIDE": None,
		"EXPONENT": None,
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": "z := NOT ● term",
		"LPAREN": "term := LPAREN ● predicate RPAREN",
		"RPAREN": None,
		"NUMBER": "term := NUMBER ● ",
		"BOOL": "term := BOOL ● ",
		"\x18": None,
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": "x := y GREATER y ● ",
		"z": "y := z ● AND z",
		"term": "z := term ● ",
		"\x19": None,
	},
	"x := y GREATER y ● ": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": ('x', 3),
		"WHERE": None,
		"ID": None,
		"COMMA": None,
		"PLUS": ('x', 3),
		"MINUS": ('x', 3),
		"DIVIDE": ('x', 3),
		"EXPONENT": ('x', 3),
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": None,
		"LPAREN": None,
		"RPAREN": ('x', 3),
		"NUMBER": None,
		"BOOL": None,
		"\x18": ('x', 3),
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": None,
		"\x19": None,
	},
	"x := y GREATEREQ ● y": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": None,
		"WHERE": None,
		"ID": "term := ID ● ",
		"COMMA": None,
		"PLUS": "z := PLUS ● term",
		"MINUS": "z := MINUS ● term",
		"DIVIDE": None,
		"EXPONENT": None,
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": "z := NOT ● term",
		"LPAREN": "term := LPAREN ● predicate RPAREN",
		"RPAREN": None,
		"NUMBER": "term := NUMBER ● ",
		"BOOL": "term := BOOL ● ",
		"\x18": None,
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": "x := y GREATEREQ y ● ",
		"z": "y := z ● AND z",
		"term": "z := term ● ",
		"\x19": None,
	},
	"x := y GREATEREQ y ● ": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": ('x', 3),
		"WHERE": None,
		"ID": None,
		"COMMA": None,
		"PLUS": ('x', 3),
		"MINUS": ('x', 3),
		"DIVIDE": ('x', 3),
		"EXPONENT": ('x', 3),
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": None,
		"LPAREN": None,
		"RPAREN": ('x', 3),
		"NUMBER": None,
		"BOOL": None,
		"\x18": ('x', 3),
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": None,
		"\x19": None,
	},
	"w := x EXPONENT ● x": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": None,
		"WHERE": None,
		"ID": "term := ID ● ",
		"COMMA": None,
		"PLUS": "z := PLUS ● term",
		"MINUS": "z := MINUS ● term",
		"DIVIDE": None,
		"EXPONENT": None,
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": "z := NOT ● term",
		"LPAREN": "term := LPAREN ● predicate RPAREN",
		"RPAREN": None,
		"NUMBER": "term := NUMBER ● ",
		"BOOL": "term := BOOL ● ",
		"\x18": None,
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": "w := x EXPONENT x ● ",
		"y": "x := y ● EQUALS y",
		"z": "y := z ● AND z",
		"term": "z := term ● ",
		"\x19": None,
	},
	"w := x EXPONENT x ● ": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": None,
		"WHERE": None,
		"ID": None,
		"COMMA": None,
		"PLUS": ('w', 3),
		"MINUS": ('w', 3),
		"DIVIDE": None,
		"EXPONENT": None,
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": None,
		"LPAREN": None,
		"RPAREN": ('w', 3),
		"NUMBER": None,
		"BOOL": None,
		"\x18": ('w', 3),
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": None,
		"\x19": None,
	},
	"query := SELECT WILDCARD FROM idlist WHERE ● predicate": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": None,
		"WHERE": None,
		"ID": "term := ID ● ",
		"COMMA": None,
		"PLUS": "z := PLUS ● term",
		"MINUS": "z := MINUS ● term",
		"DIVIDE": None,
		"EXPONENT": None,
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": "z := NOT ● term",
		"LPAREN": "term := LPAREN ● predicate RPAREN",
		"RPAREN": None,
		"NUMBER": "term := NUMBER ● ",
		"BOOL": "term := BOOL ● ",
		"\x18": None,
		"query": None,
		"idlist": None,
		"predicate": "query := SELECT WILDCARD FROM idlist WHERE predicate ● ",
		"w": "predicate := w ● PLUS w",
		"x": "w := x ● WILDCARD x",
		"y": "x := y ● EQUALS y",
		"z": "y := z ● AND z",
		"term": "z := term ● ",
		"\x19": None,
	},
	"query := SELECT WILDCARD FROM idlist WHERE predicate ● ": {
		"SELECT": None,
		"FROM": None,
		"WILDCARD": None,
		"WHERE": None,
		"ID": None,
		"COMMA": None,
		"PLUS": None,
		"MINUS": None,
		"DIVIDE": None,
		"EXPONENT": None,
		"EQUALS": None,
		"NEQUALS": None,
		"LESS": None,
		"LESSEQ": None,
		"GREATER": None,
		"GREATEREQ": None,
		"AND": None,
		"OR": None,
		"NOT": None,
		"LPAREN": None,
		"RPAREN": None,
		"NUMBER": None,
		"BOOL": None,
		"\x18": ('query', 6),
		"query": None,
		"idlist": None,
		"predicate": None,
		"w": None,
		"x": None,
		"y": None,
		"z": None,
		"term": None,
		"\x19": None,
	},
}
p.start = list(p.table.keys())[0]
def action1():
    tables = p.semstack[0]
    if len(tables) == 1:
        p.semstack = [RAT.Projection(p.semstack[1], p.semstack[0])] + p.semstack[2:]
    else:
        t = RAT.Identifier(tables[0])
        for table in tables[1:]:
            t = RAT.CrossProduct(t, RAT.Identifier(table))
        p.semstack = [RAT.Projection(p.semstack[1], t)] + p.semstack[2:]

def action2():
    p.semstack = [[p.currentToken]] + p.semstack

def action3():
    p.semstack = [p.semstack[0] + [p.currentToken]] + p.semstack[1:]

def action4():
    p.semstack = [RAT.Binary(p.semstack[1], p.semstack[0], '+')] + p.semstack[2:]

def action5():
    p.semstack = [RAT.Binary(p.semstack[1], p.semstack[0], '-')] + p.semstack[2:]

def action6():
    p.semstack = [RAT.Binary(p.semstack[1], p.semstack[0], '*')] + p.semstack[2:]

def action7():
    p.semstack = [RAT.Binary(p.semstack[1], p.semstack[0], '/')] + p.semstack[2:]

def action8():
    p.semstack = [RAT.Binary(p.semstack[1], p.semstack[0], '**')] + p.semstack[2:]

def action9():
    p.semstack = [RAT.Binary(p.semstack[1], p.semstack[0], '=')] + p.semstack[2:]

def action10():
    p.semstack = [RAT.Binary(p.semstack[1], p.semstack[0], '<>')] + p.semstack[2:]

def action11():
    p.semstack = [RAT.Binary(p.semstack[1], p.semstack[0], '<')] + p.semstack[2:]

def action12():
    p.semstack = [RAT.Binary(p.semstack[1], p.semstack[0], '<=')] + p.semstack[2:]

def action13():
    p.semstack = [RAT.Binary(p.semstack[1], p.semstack[0], '>')] + p.semstack[2:]

def action14():
    p.semstack = [RAT.Binary(p.semstack[1], p.semstack[0], '>=')] + p.semstack[2:]

def action15():
    p.semstack = [RAT.Binary(p.semstack[1], p.semstack[0], 'AND')] + p.semstack[2:]

def action16():
    p.semstack = [RAT.Binary(p.semstack[1], p.semstack[0], 'OR')] + p.semstack[2:]

def action17():
    p.semstack = [RAT.Unary(p.semstack[0], 'NOT')] + p.semstack[1:]

def action18():
    p.semstack = [RAT.Unary(p.semstack[0], '-')] + p.semstack[1:]

def action19():
    p.semstack = [RAT.Unary(p.semstack[0], '+')] + p.semstack[1:]

def action20():
    p.semstack = [RAT.Number(p.currentToken)] + p.semstack

def action21():
    p.semstack = [RAT.Identifier(p.currentToken)] + p.semstack

def action22():
    p.semstack = [RAT.Boolean(p.currentToken)] + p.semstack

def action23():
    tables = p.semstack[0]
    t = RAT.Identifier(tables[0])
    if len(tables) == 1:
        p.semstack = [t] + p.semstack[1:]
    else:
        for table in tables[1:]:
            t = RAT.CrossProduct(t, RAT.Identifier(table))
        p.semstack = [t] + p.semstack[1:]

def action24():
    tables = p.semstack[1]
    t = RAT.Identifier(tables[0])
    if len(tables) == 1:
        sel = RAT.Selection(t, p.semstack[0])
        p.semstack = [RAT.Projection(p.semstack[2], sel)] + p.semstack[3:]
    else:
        for table in tables[1:]:
            t = RAT.CrossProduct(t, RAT.Identifier(table))
        sel = RAT.Selection(t, p.semstack[0])
        p.semstack = [RAT.Projection(p.semstack[2], sel)] + p.semstack[3:]

def action25():
    tables = p.semstack[1]
    t = RAT.Identifier(tables[0])
    if len(tables) == 1:
        p.semstack = [RAT.Selection(t, p.semstack[0])] + p.semstack[2:]
    else:
        for table in tables[1:]:
            t = RAT.CrossProduct(t, RAT.Identifier(table))
        sel = RAT.Selection(t, p.semstack[0])
        p.semstack = [RAT.Selection(t, p.semstack[0])] + p.semstack[2:]

p.actions = {
	"query := SELECT idlist FROM idlist ● ": action1,
	"query := SELECT WILDCARD FROM idlist ● ": action23,
	"query := SELECT idlist FROM idlist WHERE predicate ● ": action24,
	"query := SELECT WILDCARD FROM idlist WHERE predicate ● ": action25,
	"idlist := ID ● ": action2,
	"idlist := idlist COMMA ID ● ": action3,
	"predicate := w PLUS w ● ": action4,
	"predicate := w MINUS w ● ": action5,
	"w := x WILDCARD x ● ": action6,
	"w := x DIVIDE x ● ": action7,
	"w := x EXPONENT x ● ": action8,
	"x := y EQUALS y ● ": action9,
	"x := y NEQUALS y ● ": action10,
	"x := y LESS y ● ": action11,
	"x := y LESSEQ y ● ": action12,
	"x := y GREATER y ● ": action13,
	"x := y GREATEREQ y ● ": action14,
	"y := z AND z ● ": action15,
	"y := z OR z ● ": action16,
	"z := NOT term ● ": action17,
	"z := MINUS term ● ": action18,
	"z := PLUS term ● ": action19,
	"term := NUMBER ● ": action20,
	"term := ID ● ": action21,
	"term := BOOL ● ": action22,
}
